### ISSUE TITLE
editTopo.py for 0.1deg

### ISSUE THREAD

**Issue by julia-neme** [COSIMA/topogtools#2]
I want to change topog.nc file using editTopo. Specifically, I want to extend a ridgeline of about 10deg in longitude. 

I could use the script for the 1deg because it didn't involve much clicking.. but for the 0.1deg it is a bit exhausting. Is it possible to add a utility that allows to change multiple grid cells with one click?

**Comment by aekiss** [comment]
You could write a script to generate an ascii file of edits, and can apply them with `./editTopo.py --apply`.
See `./editTopo.py -h` for details. 

You could also try `bulldozer` from this repo but I don't know much about that.

Note that you'll need to regenerate a bunch of other files when you change bathymetry. You'll need to do a subset of what's done in https://github.com/COSIMA/make_025deg_topo and https://github.com/COSIMA/make_1deg_topo
(there isn't one for 0.1 deg).

Are you changing the land mask? It gets even more tricky if you do that.

**Comment by russfiedler** [comment]
Bit exhausting? I think 22K hand edits is a bit exhausting... :)

There is also a Fortran program edit_topo.f90 that I uploaded a while back in `/g/data/hh5/tmp/cosima/bathymetry/tools/common/src/edit_topo.f90`. It will take multiple edits in an ascii file of the form

istart iend jstart jend new_depth
...

with the edits applied in sequence. If you're just applying a ridge of constant height all it takes is one line.

If you're after something a bit more complicated (e.g. adding a constant and/or adding some smoothing) I might be able to whip up something quickly with Ferret but you'll have to run the other tools yourself to ensure the validity of the files for MOM as @aekiss mentions above.

**Comment by julia-neme** [comment]
Thank you @aekiss and @russfiedler, I will try with with this or the method posted on slack. Much better than clicking!

**Comment by aekiss** [comment]
closing - @julia-neme: feel free to reopen if you need to discuss further
