### ISSUE TITLE
Possible bug introduced in `topog2mask.py`

### ISSUE THREAD

**Issue by rmholmes** [COSIMA/topogtools#7]
[Dietmar Dommenget is trying to change the topography in ACCESS-OM2](https://forum.access-hive.org.au/t/access-coupled-n48-for-deep-paleo/529/36?u=rmholmes) using the wiki instructions at https://github.com/COSIMA/access-om2/wiki/Tutorials#changing-the-bathymetry-land-sea-mask-and-oasis-remapping-weights and run into a bug:
```
python topog2mask.py topog.nc kmt.nc ocean_mask.nc
Traceback (most recent call last):
File “/g/data/w40/dxd565/access-om/experiments/no-drake-passage/input/…/…/…/tools/topogtools/topog2mask.py”, line 63, in
sys.exit(main())
File “/g/data/w40/dxd565/access-om/experiments/no-drake-passage/input/…/…/…/tools/topogtools/topog2mask.py”, line 59, in main
make_mask(args.topog, args.cice_mask, args.fraction, ice=True)
File “/g/data/w40/dxd565/access-om/experiments/no-drake-passage/input/…/…/…/tools/topogtools/topog2mask.py”, line 29, in make_mask
mask[:] = np.where((tf.variables[‘frac’][:] < frac) | (tf.variables[‘depth’][:] <= 0.0), 0, 1)
KeyError: ‘frac’
```

It looks like it's related to changes @micaeljtoliveira made [here](https://github.com/COSIMA/topogtools/commit/03cfc66171a0670a1f6998f5b8b843b33b392618) - specifically introducing a `frac` argument to `topog2mask.py`. The routine `make_mask` is looking for a `frac` variable in the `topog.nc` netcdf files which doesn't exist  (in old versions of the file).

@micaeljtoliveira I'm not sure what's going on here? I just advised Dietmar to use an older version of the code.

**Comment by micaeljtoliveira** [comment]
Ah, yes, my changes are not backward compatible. Sorry about that. Should not be too hard to fix this though.
